// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Code.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250110112657_AddUser")]
    partial class AddUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Code.Models.AcademicProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Academics");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            FacultyId = 1,
                            ProgramName = "BSc Microbiology"
                        },
                        new
                        {
                            Id = 3,
                            FacultyId = 1,
                            ProgramName = "BSc Physics"
                        },
                        new
                        {
                            Id = 4,
                            FacultyId = 1,
                            ProgramName = "BSc Chemistry"
                        },
                        new
                        {
                            Id = 5,
                            FacultyId = 1,
                            ProgramName = "BSc Mathematics"
                        },
                        new
                        {
                            Id = 6,
                            FacultyId = 1,
                            ProgramName = "BSc Environmental Science"
                        },
                        new
                        {
                            Id = 7,
                            FacultyId = 2,
                            ProgramName = "BBA"
                        },
                        new
                        {
                            Id = 8,
                            FacultyId = 2,
                            ProgramName = "MBA"
                        },
                        new
                        {
                            Id = 9,
                            FacultyId = 2,
                            ProgramName = "BBS"
                        },
                        new
                        {
                            Id = 10,
                            FacultyId = 2,
                            ProgramName = "MBS"
                        },
                        new
                        {
                            Id = 11,
                            FacultyId = 2,
                            ProgramName = "BIM"
                        },
                        new
                        {
                            Id = 12,
                            FacultyId = 3,
                            ProgramName = "BA Sociology"
                        },
                        new
                        {
                            Id = 13,
                            FacultyId = 3,
                            ProgramName = "BA English"
                        },
                        new
                        {
                            Id = 14,
                            FacultyId = 3,
                            ProgramName = "BA Political Science"
                        },
                        new
                        {
                            Id = 15,
                            FacultyId = 3,
                            ProgramName = "BA Economics"
                        },
                        new
                        {
                            Id = 16,
                            FacultyId = 3,
                            ProgramName = "MA Sociology"
                        },
                        new
                        {
                            Id = 17,
                            FacultyId = 4,
                            ProgramName = "BSc CSIT"
                        },
                        new
                        {
                            Id = 18,
                            FacultyId = 4,
                            ProgramName = "BSc Microbiology"
                        },
                        new
                        {
                            Id = 19,
                            FacultyId = 4,
                            ProgramName = "BSc Environmental Science"
                        },
                        new
                        {
                            Id = 20,
                            FacultyId = 5,
                            ProgramName = "BBA"
                        },
                        new
                        {
                            Id = 21,
                            FacultyId = 5,
                            ProgramName = "MBA"
                        },
                        new
                        {
                            Id = 22,
                            FacultyId = 6,
                            ProgramName = "BA English"
                        },
                        new
                        {
                            Id = 23,
                            FacultyId = 6,
                            ProgramName = "BA Sociology"
                        },
                        new
                        {
                            Id = 24,
                            FacultyId = 7,
                            ProgramName = "BEng Computer Engineering"
                        },
                        new
                        {
                            Id = 25,
                            FacultyId = 7,
                            ProgramName = "BEng Civil Engineering"
                        },
                        new
                        {
                            Id = 26,
                            FacultyId = 7,
                            ProgramName = "BEng Electrical Engineering"
                        },
                        new
                        {
                            Id = 27,
                            FacultyId = 7,
                            ProgramName = "BEng Electronics and Communication Engineering"
                        },
                        new
                        {
                            Id = 28,
                            FacultyId = 8,
                            ProgramName = "LLB"
                        },
                        new
                        {
                            Id = 29,
                            FacultyId = 9,
                            ProgramName = "BEd"
                        },
                        new
                        {
                            Id = 30,
                            FacultyId = 9,
                            ProgramName = "MEd"
                        },
                        new
                        {
                            Id = 31,
                            FacultyId = 10,
                            ProgramName = "BFA"
                        },
                        new
                        {
                            Id = 32,
                            FacultyId = 11,
                            ProgramName = "BSc Agriculture"
                        },
                        new
                        {
                            Id = 33,
                            FacultyId = 12,
                            ProgramName = "BSc Nursing"
                        },
                        new
                        {
                            Id = 34,
                            FacultyId = 12,
                            ProgramName = "BPH"
                        });
                });

            modelBuilder.Entity("Code.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyName = "Faculty of Humanities and Social Sciences",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 2,
                            FacultyName = "Faculty of Science",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 3,
                            FacultyName = "Faculty of Management",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 4,
                            FacultyName = "Faculty of Education",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 5,
                            FacultyName = "Faculty of Law",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 6,
                            FacultyName = "Faculty of Fine Arts",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 7,
                            FacultyName = "Faculty of Engineering",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 8,
                            FacultyName = "Faculty of Ayurveda and Alternative Medicine",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 9,
                            FacultyName = "Faculty of Agriculture",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 10,
                            FacultyName = "Faculty of Health Sciences",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 11,
                            FacultyName = "Faculty of Humanities and Social Sciences",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 12,
                            FacultyName = "Faculty of Science",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 13,
                            FacultyName = "Faculty of Management",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 14,
                            FacultyName = "Faculty of Education",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 15,
                            FacultyName = "Faculty of Law",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 16,
                            FacultyName = "Faculty of Fine Arts",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 17,
                            FacultyName = "Faculty of Engineering",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 18,
                            FacultyName = "Faculty of Ayurveda and Alternative Medicine",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 19,
                            FacultyName = "Faculty of Agriculture",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 20,
                            FacultyName = "Faculty of Health Sciences",
                            UniversityId = 2
                        });
                });

            modelBuilder.Entity("Code.Models.Pdf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PdfTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pdfs");
                });

            modelBuilder.Entity("Code.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PdfAcademicProgram", b =>
                {
                    b.Property<int>("PdfId")
                        .HasColumnType("int");

                    b.Property<int>("AcademicProgramId")
                        .HasColumnType("int");

                    b.HasKey("PdfId", "AcademicProgramId");

                    b.HasIndex("AcademicProgramId");

                    b.ToTable("PdfAcademicPrograms");
                });

            modelBuilder.Entity("University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UniversityName = "TU"
                        },
                        new
                        {
                            Id = 2,
                            UniversityName = "PU"
                        });
                });

            modelBuilder.Entity("Code.Models.AcademicProgram", b =>
                {
                    b.HasOne("Code.Models.Faculty", "Faculty")
                        .WithMany("AcademicPrograms")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Code.Models.Faculty", b =>
                {
                    b.HasOne("University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("Code.Models.Pdf", b =>
                {
                    b.HasOne("Code.Models.User", "User")
                        .WithMany("UploadedPdfs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PdfAcademicProgram", b =>
                {
                    b.HasOne("Code.Models.AcademicProgram", "AcademicProgram")
                        .WithMany("PdfAcademicPrograms")
                        .HasForeignKey("AcademicProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Code.Models.Pdf", "Pdf")
                        .WithMany("PdfAcademicPrograms")
                        .HasForeignKey("PdfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicProgram");

                    b.Navigation("Pdf");
                });

            modelBuilder.Entity("Code.Models.AcademicProgram", b =>
                {
                    b.Navigation("PdfAcademicPrograms");
                });

            modelBuilder.Entity("Code.Models.Faculty", b =>
                {
                    b.Navigation("AcademicPrograms");
                });

            modelBuilder.Entity("Code.Models.Pdf", b =>
                {
                    b.Navigation("PdfAcademicPrograms");
                });

            modelBuilder.Entity("Code.Models.User", b =>
                {
                    b.Navigation("UploadedPdfs");
                });

            modelBuilder.Entity("University", b =>
                {
                    b.Navigation("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
